# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OpenDota' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenDota
  pod 'AppCenter/Push', '~> 1.1.0'
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
end
