# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenDota' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenDota
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

end
